package com.example.demo.model.enums;

import com.example.demo.dto.CurrencyDTO;

public enum Currency {
    AED("AED", "AED"),
    AFN("AFN", "Afs"),
    ALL("ALL", "L"),
    AMD("AMD", "AMD"),
    ANG("ANG", "ANG"),
    AOA("AOA", "Kz"),
    ARS("ARS", "$"),
    AUD("AUD", "$"),
    AWG("AWG", "AWG"),
    AZN("AZN", "AZN"),
    BAM("BAM", "KM"),
    BBD("BBD", "Bds$"),
    BDT("BDT", "BDT"),
    BGN("BGN", "BGN"),
    BHD("BHD", "BHD"),
    BIF("BIF", "FBu"),
    BMD("BMD", "BD$"),
    BND("BND", "B$"),
    BOB("BOB", "Bs."),
    BRL("BRL", "R$"),
    BSD("BSD", "B$"),
    BTN("BTN", "Nu."),
    BWP("BWP", "P"),
    BYR("BYR", "Br"),
    BZD("BZD", "BZ$"),
    CAD("CAD", "$"),
    CDF("CDF", "F"),
    CHF("CHF", "Fr."),
    CLP("CLP", "$"),
    CNY("CNY", "CNY"),
    COP("COP", "Col$"),
    CRC("CRC", "CRC"),
    CUC("CUC", "$"),
    CVE("CVE", "Esc"),
    CZK("CZK", "CZK"),
    DJF("DJF", "Fdj"),
    DKK("DKK", "Kr"),
    DOP("DOP", "RD$"),
    DZD("DZD", "DZD"),
    EEK("EEK", "KR"),
    EGP("EGP", "EGP"),
    ERN("ERN", "Nfa"),
    ETB("ETB", "Br"),
    EUR("EUR", "€"),
    FJD("FJD", "FJ$"),
    FKP("FKP", "FKP"),
    GBP("GBP", "£"),
    GEL("GEL", "GEL"),
    GHS("GHS", "GHS"),
    GIP("GIP", "GIP"),
    GMD("GMD", "D"),
    GNF("GNF", "FG"),
    GQE("GQE", "CFA"),
    GTQ("GTQ", "Q"),
    GYD("GYD", "GY$"),
    HKD("HKD", "HK$"),
    HNL("HNL", "L"),
    HRK("HRK", "kn"),
    HTG("HTG", "G"),
    HUF("HUF", "Ft"),
    IDR("IDR", "Rp"),
    ILS("ILS", "ILS"),
    INR("INR", "INR"),
    IQD("IQD", "IQD"),
    IRR("IRR", "IRR"),
    ISK("ISK", "kr"),
    JMD("JMD", "J$"),
    JOD("JOD", "JOD"),
    JPY("JPY", "JPY"),
    KES("KES", "KSh"),
    KGS("KGS", "KSG"),
    KHR("KHR", "KHR"),
    KMF("KMF", "KMF"),
    KPW("KPW", "W"),
    KRW("KRW", "W"),
    KWD("KWD", "KWD"),
    KYD("KYD", "KY$"),
    KZT("KZT", "T"),
    LAK("LAK", "KN"),
    LBP("LBP", "LBP"),
    LKR("LKR", "Rs"),
    LRD("LRD", "L$"),
    LSL("LSL", "M"),
    LTL("LTL", "Lt"),
    LVL("LVL", "Ls"),
    LYD("LYD", "LD"),
    MAD("MAD", "MAD"),
    MDL("MDL", "MDL"),
    MGA("MGA", "FMG"),
    MKD("MKD", "MKD"),
    MMK("MMK", "K"),
    MNT("MNT", "MNT"),
    MOP("MOP", "P"),
    MRO("MRO", "UM"),
    MUR("MUR", "Rs"),
    MVR("MVR", "Rf"),
    MWK("MWK", "MK"),
    MXN("MXN", "$"),
    MYR("MYR", "RM"),
    MZM("MZM", "MTn"),
    NAD("NAD", "N$"),
    NGN("NGN", "NGN"),
    NIO("NIO", "C$"),
    NOK("NOK", "kr"),
    NPR("NPR", "NRs"),
    NZD("NZD", "NZ$"),
    OMR("OMR", "OMR"),
    PAB("PAB", "B./"),
    PEN("PEN", "S/."),
    PGK("PGK", "K"),
    PHP("PHP", "PHP"),
    PKR("PKR", "Rs."),
    PLN("PLN", "PLN"),
    PYG("PYG", "PYG"),
    QAR("QAR", "QR"),
    RON("RON", "L"),
    RSD("RSD", "din."),
    RUB("RUB", "R"),
    SAR("SAR", "SR"),
    SBD("SBD", "SI$"),
    SCR("SCR", "SR"),
    SDG("SDG", "SDG"),
    SEK("SEK", "kr"),
    SGD("SGD", "S$"),
    SHP("SHP", "SHP"),
    SLL("SLL", "Le"),
    SOS("SOS", "Sh."),
    SRD("SRD", "$"),
    SYP("SYP", "LS"),
    SZL("SZL", "E"),
    THB("THB", "THB"),
    TJS("TJS", "TJS"),
    TMT("TMT", "m"),
    TND("TND", "DT"),
    TRY("TRY", "TRY"),
    TTD("TTD", "TT$"),
    TWD("TWD", "NT$"),
    TZS("TZS", "TZS"),
    UAH("UAH", "UAH"),
    UGX("UGX", "USh"),
    USD("USD", "$"),
    UYU("UYU", "$U"),
    UZS("UZS", "UZS"),
    VEB("VEB", "Bs"),
    VND("VND", "VND"),
    VUV("VUV", "VT"),
    WST("WST", "WS$"),
    XAF("XAF", "CFA"),
    XCD("XCD", "EC$"),
    XDR("XDR", "SDR"),
    XOF("XOF", "CFA"),
    XPF("XPF", "F"),
    YER("YER", "YER"),
    ZAR("ZAR", "R"),
    ZMK("ZMK", "ZK"),
    ZWR("ZWR", "Z$");

    private String key;
    private String symbol;

    Currency(String key, String symbol) {
        this.key = key;
        this.symbol = symbol;
    }

    public String getKey() {
        return key;
    }

    public String getSymbol() {
        return symbol;
    }

    public CurrencyDTO toDTO() {
        return CurrencyDTO.builder()
                .code(key)
                .symbol(symbol)
                .build();
    }
}
